import "../../globals.css";
import type { Metadata } from "next";
import AsideBar from "../../components/AsideBar";
import HeaderMenu from "../../components/HeaderMenu";
import UserProfile from "@/app/components/UserProfile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-full flex flex-col">
          <div className="h-[100vh] max-h-[100vh]">
            <div className="flex flex-row w-full bg-[#1c1c1c] h-[100vh] max-h-[100vh] overflow-hidden">
              <AsideBar />
              <main className="col-span-9 mx-auto w-full bg-[#202020]">
                <HeaderMenu />
                <main className="flex h-[95%] flex-col gap-5 overflow-y-scroll">
                  <div className="max-w-[600px] box-border w-[100%] mx-auto flex justify-center">
                    <div className="border border-[#2e2e2e] border-t-0 border-b-0 w-max">
                      <UserProfile id={params.id} />
                      <main>{children}</main>
                    </div>
                  </div>
                </main>
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
