import "../globals.css";
import type { Metadata } from "next";
import AsideBar from "../components/AsideBar";
import HeaderMenu from "../components/HeaderMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-full flex flex-col">
          <div className="h-[100vh] max-h-[100vh]">
            <div className="flex flex-row w-full bg-[#1c1c1c] h-[100vh] max-h-[100vh] overflow-hidden">
              <AsideBar />
              <main className="col-span-9 mx-auto w-full bg-[#202020]">
                <HeaderMenu />
                <main className="flex h-[95%] flex-col overflow-y-scroll">
                  {children}
                </main>
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
